name: CD - Build and Deploy to Kubernetes

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        shell: bash
        run: |
          docker build -t flask-app:${{ github.sha }} .

      - name: Load image into Kubernetes node
        shell: bash
        run: |
          docker save -o flask-app-ci.tar flask-app:${{ github.sha }}
          docker cp flask-app-ci.tar desktop-control-plane:/flask-app-ci.tar
          MSYS_NO_PATHCONV=1 docker exec desktop-control-plane ctr -n k8s.io images import //flask-app-ci.tar

      - name: Deploy to Kubernetes
        shell: bash
        run: |
          kubectl set image deployment/flask-app-deployment flask-app=flask-app:${{ github.sha }}
          kubectl rollout status deployment/flask-app-deployment

      - name: Verify deployment
        shell: bash
        run: |
          curl http://localhost:5000
          curl http://localhost:5000/health